main: com.amoebaman.engrave.Engrave

name: Engrave
author: AmoebaMan
version: 1.1
description: Allows messages to be engraved on blocks and read at later dates

commands:
  engrave:
    aliases: [etch, carve]
    description: Engraves text into a block
    usage: /engrave <message...>
    permission: engrave.use
  debug-engrave:
    permission: engrave.debug
    
permissions:
  engrave.use:
    description: Allows the player to engrave on blocks
    default: true
  engrave.read:
    description: Allows the player to read engravings
    default: true
  engrave.degrade:
    description: Allows the player to degrade engravings
    default: true
  engrave.debug:
    description: Allows the player to debug engravings
    default: op